2016-10-20 18:56:47,156 main ERROR util.ApplicationException - Error al conectar a la DB
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_40]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_40]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_40]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_40]
	at data.FactoryConexion.getConn(FactoryConexion.java:40) [bin/:?]
	at data.PersonajeAdapter.GetByNombre(PersonajeAdapter.java:53) [bin/:?]
	at logic.PersonajeLogic.GetByNombre(PersonajeLogic.java:72) [bin/:?]
	at console.Prueba.main(Prueba.java:16) [bin/:?]
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_40]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_40]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_40]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_40]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_40]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_40]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_40]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[mysql-connector-java-5.1.39-bin.jar:5.1.39]
	... 18 more
